### ISSUE TITLE
Feature request: Choice of console

### ISSUE THREAD

**Issue by xymox12** [lanayotech/vagrant-manager-windows#33] opened 2016-09-07 07:53 UTC
Hi

First of - thanks for developing this great tool.

Currently when you open 'SSH' or 'Open in Terminal' you are forced to use Window's default cmd console. 

Not sure if this will work but could you add a new menu choice 'Open in ...' that the user can link to the console of their choice, or change the preferences to allow the default console to be changed by the user to the one of their choice (e.g ConEmu)?

Thanks

**Comment by xymox12** [comment] 2016-09-07 08:05
Sorry - just realised this is a duplicate of issue #5! 

Clearly too little coffee in my system!

**Comment by amitailanciano** [comment] 2017-03-04 06:53
duplicate of #5

**Closed by amitailanciano** 2017-03-04 06:53 UTC
